# App
spring.application.name=faketrace
server.port=8080

# Conexion Neo4j
spring.neo4j.uri=neo4j+s://2be0346a.databases.neo4j.io
spring.neo4j.authentication.username=2be0346a
spring.neo4j.authentication.password=QFtvSX_ooREjlKM-hONjwbm1C_fo7fAWs0Ln3Dx9JZE
spring.data.neo4j.database=2be0346a

# Archivos estaticos
spring.web.resources.static-locations=classpath:/static/

# Login basico
faketrace.auth.username=admin
faketrace.auth.password=admin123
